provider "aws"{
  region = "ap-south-1"
  access_key = "AKIARKQKGIXFMKSTXVE6"
  secret_key = "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"
  

}


resource "aws_s3_bucket" "storgae" {
bucket = "shaanumai"

}
